name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate_pressed:
    name: Validate preseed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure environment
        run: |
          sudo apt-get update
          sudo apt-get install debconf-utils
      - name: Validate preseed
        run: debconf-set-selections -v -c iso_tools/preseed.seed

  build_iso:
    name: Build ISO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Test ISO
        run: ./build.sh
